# Linear Algebra Practice

Notes:
- vector = 1D array
- matrix = 2D array
- dot product = combine matching entries
- identity matrix = like 1 for matrices
- inverse = undo transformation

In [1]:
import numpy as np

Note: `shape` tells the dimensions of an array. `dot()` is used for vector/matrix multiplication.

## 1. Dot product / matrix-vector multiplication

- same-size vectors -> scalar result
- matrix × vector -> new vector
- shapes must match

In [2]:
u = np.array([1, 2, 3,4])
v = np.array([5, 6,7,8])

In [3]:
u.shape[0]

4

In [4]:
v.dot(u)

np.int64(70)

In [5]:
U = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
U.shape

(3, 4)

In [6]:
U.dot(v)

array([ 70, 174, 278])

In [7]:
V = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
V.shape

(4, 3)

In [8]:
V.dot(U)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200],
       [173, 206, 239, 272]])

## 3. Identity matrix

- 1s on diagonal, 0 elsewhere
- multiplying by it does not change the value

In [9]:
I = np.eye(3)

In [10]:
V

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
V.dot(I)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

## 4. Inverse

- inverse matrix reverses the transformation
- only works if determinant is not zero
- A × A^-1 = I

In [26]:
Vs = np.array([
    [1, 2, 3],
    [0, 1, 4],
    [5, 6, 0]
])

In [27]:
np.isclose(np.linalg.det(Vs), 0)

np.False_

In [28]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

In [29]:
Vs_inv.dot(Vs)

array([[ 1.00000000e+00, -8.88178420e-15, -1.42108547e-14],
       [ 1.77635684e-15,  1.00000000e+00,  0.00000000e+00],
       [-4.44089210e-16, -8.88178420e-16,  1.00000000e+00]])

Summary:
- dot product = scalar score
- matrix × vector = transformed vector
- identity = no change
- inverse = undo operation