# NumPy Practice

Notes:
- array = structured data container
- 1D = vector, 2D = matrix
- `np.zeros`, `np.ones`, `np.full` create arrays
- operations are often element-wise
- boolean masks are used for filtering

## 1. Import

- NumPy gives arrays and vectorized math
- `import numpy as np`

In [1]:
import numpy as np

## 2. Creating arrays

- arrays can be 1D or 2D

- `np.zeros`, `np.ones`, `np.full`- `np.arange`, `np.linspace`

In [2]:
np.zeros(4)

array([0., 0., 0., 0.])

In [3]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [4]:
np.full(4,3)

array([3, 3, 3, 3])

In [5]:
a = np.array([1,5,9,11])
a


array([ 1,  5,  9, 11])

In [6]:
a[-1] = 13 

In [7]:
a

array([ 1,  5,  9, 13])

In [8]:
b = np.arange(14)

In [9]:
b + 1 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
np.linspace(0, 66, 7)

array([ 0., 11., 22., 33., 44., 55., 66.])

## 3. Multi-dimensional arrays

- indexing by row/column
- slices with `:`
- assign values to selected positions

In [11]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
n = np.array([
    [1,20,3],
    [4,50,6],
    [7,8,90]
])

In [14]:
n[0,1] = 2
n[1,1] = 5
n[2,2] = 9
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
n[1] = [6,5,4]
n

array([[1, 2, 3],
       [6, 5, 4],
       [7, 8, 9]])

In [16]:
n[:,2]

array([3, 4, 9])

In [17]:
n[:,1] = [10,60,70]
n

array([[ 1, 10,  3],
       [ 6, 60,  4],
       [ 7, 70,  9]])

In [18]:
n[:,2] = [100, 600, 700]
n

array([[  1,  10, 100],
       [  6,  60, 600],
       [  7,  70, 700]])

## 4. Random arrays

- use `seed` for reproducibility

- `np.random.rand` for floats- `np.random.randint` for integers

In [37]:
np.random.seed(42)
r = np.random.rand(4,3)
r

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985]])

In [38]:
100 * r

array([[37.45401188, 95.07143064, 73.19939418],
       [59.86584842, 15.60186404, 15.59945203],
       [ 5.80836122, 86.61761458, 60.11150117],
       [70.80725778,  2.05844943, 96.99098522]])

In [42]:
np.random.seed(42)
np.random.randint(low=0, high=10, size=(3,4))

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]], dtype=int32)

## 5. Element-wise operations

- works for arrays of same shape
- arithmetic is applied to each element

In [43]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [44]:
b = a**2 / 2
b

array([0. , 0.5, 2. , 4.5, 8. ])

In [45]:
c = b - a
c

array([ 0. , -0.5,  0. ,  1.5,  4. ])

## 6. Comparison operations

- boolean arrays can be used as masks
- comparisons return booleans

In [46]:
b[2] > a[2]

np.False_

In [47]:
b > 2

array([False, False, False,  True,  True])

In [48]:
a > b

array([False,  True, False, False, False])

In [49]:
a[a>b]

array([1])

In [50]:
a[a>=b]

array([0, 1, 2])

In [51]:
b[a<b]

array([4.5, 8. ])

## 7. Summary statistics

- useful for quick data summary
- `mean`, `std`, `min`, `max`

In [52]:
a

array([0, 1, 2, 3, 4])

In [55]:
a.std()

np.float64(1.4142135623730951)

In [58]:
n.min()

np.int64(1)