[Setup instructions](./Summary.md#topic-notebooks)


In [ ]:
import numpy as np


# Linear Regression

1. Linear regression function

In [324]:
def linear_regression(xi):
    n = len(xi)

    pred = w0

    for j in range(n):
        pred = pred + w[j] * xi[j]

    return pred

2. From log price back to dollars

In [325]:
np.expm1(12.312)

np.float64(222347.2221101062)

In [326]:
np.log1p(222347.2221101062)

np.float64(12.312)

# Linear Regression Vector

1. Linear regression for all cars

In [327]:
x1  = [1, 148, 24, 1385]
x2  = [1, 132, 25, 2031]
x10 = [1, 453, 11, 86]

X = [x1, x2, x10]
X = np.array(X)
X

array([[   1,  148,   24, 1385],
       [   1,  132,   25, 2031],
       [   1,  453,   11,   86]])

In [328]:
w0 = 7.17
w = [0.01, 0.04, 0.002]
w_new = [w0] + w

2. Linear regression function (Matrix-Vector multiplication)

In [329]:
def linear_regression(X):
    return X.dot(w_new)

In [330]:
linear_regression(X)

array([12.38 , 13.552, 12.312])

# Training Linear Regression

1. Solving for the weights

- g(X) = Xw
- Xw ~= y

- Suppose X is invertible

- -X⁻¹Xw = X⁻¹y
- -> Iw = X⁻¹y
- -> w = X⁻¹y

However X is in rectangular in our case (m rows and n+1 columns)
- -> The solution to this system simply doesn't exist.

2. The Gram matrix and the normal equation

Closest possible approximate solution: 
- Multiply both of Xw ~= y by the transpose of X: &emsp; <font color="green">XᵀXw = Xᵀy</font>
- The matrix XᵀX is called the gram matrix
- It has n+1 columns and n+1 rows
- We multiply both sides by (XᵀX)⁻¹: &emsp; <font color="green">(XᵀX)⁻¹XᵀXw = (XᵀX)⁻¹Xᵀy</font>
- Then we become this normal equation: &emsp; <font color="red">w = (XᵀX)⁻¹Xᵀy</font>

- This w is not the solution to the original system
- That solution doesn't exist
- But it is the closest possible solution.

3. Implementing the normal equation

In [331]:
X = [
    [148, 24, 1385],
    [132, 25, 2031],
    [453, 11, 86],
    [158, 24, 185],
    [172, 25, 201],
    [413, 11, 86],
    [38,  54, 185],
    [142, 25, 431],
    [453, 31, 86],
]
X = np.array(X)
X

array([[ 148,   24, 1385],
       [ 132,   25, 2031],
       [ 453,   11,   86],
       [ 158,   24,  185],
       [ 172,   25,  201],
       [ 413,   11,   86],
       [  38,   54,  185],
       [ 142,   25,  431],
       [ 453,   31,   86]])

- First step of the normal equation is the Gram matrix:

In [332]:
XTX = X.T.dot(X)

- Then we compute its inverse:

In [333]:
XTX_inv = np.linalg.inv(XTX)

- Sanity-check that the inverse is correct:

In [334]:
XTX_inv.dot(XTX).round(1)

array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [ 0.,  0.,  1.]])

- Target Vector y

In [335]:
y = [100, 200, 150, 250, 100, 200, 150, 250, 120]

- Puitting all together, the normal equation gives us the weights:

In [336]:
w_full = XTX_inv.dot(X.T).dot(y)

- We forgot the bias term
- To include it, we add a column of ones to X and repeat the same steps:

In [337]:
ones = np.ones(X.shape[0])
# np.column_stack to add the ones column to the first column of X
X = np.column_stack([ones, X])
XTX = X.T.dot(X)
XTX_inv = np.linalg.inv(XTX)
w_full = XTX_inv.dot(X.T).dot(y)

- w_full can be split into two parts if we want

In [338]:
w0 = w_full[0]
w = w_full[1:]

- The whole training in a function:

In [339]:
def train_linear_regression(X, y):
    ones = np.ones(X.shape[0])
    X = np.column_stack([ones, X])

    XTX = X.T.dot(X)
    XTX_inv = np.linalg.inv(XTX)
    w_full = XTX_inv.dot(X.T).dot(y)

    return w_full[0], w_full[1:]